### ISSUE TITLE
How to pass default environment variables into custom ssh-plugin

### ISSUE THREAD

**Issue by euclid1990** [drone-plugins/drone-ssh#11]
#### I faced this problem when custom plugins

Step 1: I have forked this repo: https://github.com/drone-plugins/drone-ssh
Step 2: I run followings command to build `/drone-ssh` binary
```
export GO15VENDOREXPERIMENT=1
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -tags netgo
```
Step 3: I built docker image with command: `docker build -t euclid1990/drone-ssh .`
Step 4: I have been configured my `.drone.yml` in my source code with custom image/plugins:
```
deploy:
  ssh:
    image: euclid1990/drone-ssh
    host: 108.61.186.xxx
    user: root
    port: 22
    sleep: 5
    commands:
      - echo hello
```
Step 5: I run drone exec in local to test: `drone exec --deploy  -i ~/.ssh/id_rsa`
But it echo below errors:
```
[DRONE] starting job #1
Error: Can't connect without a private SSH key.
[info] build failed (exit code 1)
[DRONE] finished job #1
[DRONE] exit code 1
[DRONE] job #1 failed
[DRONE] build failed
```

It seem not pass Drone `PLUGIN_KEY="$(cat ${HOME}/.ssh/id_rsa)" ` into custom ssh-plugin ? How can I read private key of drone in custom plugin ?

If I remove `image: euclid1990/drone-ssh` in .drone.yml, everything is ok !
