### ISSUE TITLE
Add Pre/Post SCP Paths

### ISSUE THREAD

**Issue by steve-gray** [drone-plugins/drone-ssh#15]
@tboerger  / @bradrydzewski 

To make the SSH plugin useful for a CI pipeline, rather than just raw 'put it somewhere else, then call it down from the target server' behaviour, this plugin needs some means to interact with the workspace. The most logical approach to this I can see is:

- Before calling the commands, copy a set of files up using the scp module. Could be passed as a list of paths/globbing rules to copy.
- After calling the commands, copy either the same paths (or a set of alternative files) or files back down to the workspace.

This allows for some interesting behaviour such as driving iOS/XCode builds, until such time that the cross-platform support is bedded in. In effect:

     pipeline:
        run_npm_install:
           image: node:6
           commands: 
                - npm install
        run_fastlane_build:
           image: drone-ssh
           .. usual ssh plugin args for keys/server ..
           copyUp:
              - **/*.*
              - !android
           copyDown:
              - **/*.*
           cwd: /builds/${DRONE_BUILD_NAME}/${DRONE_BUILD_NUMBER}
           commands:
              - fastlane ios beta

Probably bonus points involved for any kind of tarballing optimisation.

Is this an idea that people see any value in? Or am I missing a far easier way to drive this.

**Comment by tboerger** [comment]
That won't get into this plugin. The plugins are built for a single purpose, if you need to copy files use the rsync or sftp plugins and execute ssh afterwards

**Comment by bradrydzewski** [comment]
@steve-gray the rsync plugin can be used to copy files to a server and execute a command after the file transfer is complete:

```
pipeline:
  build:
    ..
  upload:
    image: plugins/rsync
    user: root
    host: foo.com
    source: copy/files/from
    target: send/files/to
    commands:
      - service nginx restart
```

you can also use the ssh and rsync plugin together for more advanced workflows:

```
pipeline:
  build:
    ..
  stop:
    image: plugins/ssh
    host: foo.com
    commands:
      - service nginx stop
  upload:
    image: plugins/rsync
    host: foo.com
    source: copy/files/from
    target: send/files/to
  start:
    image: plugins/ssh
    host: foo.com
    commands:
      - service nginx start
```

or you can use ssh commands directly from steps in your build script which gives you total control over file transfer and command execution:

```
pipeline:
  build:
    ...
  deploy:
    image: ubuntu
    commands:
      - echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - ssh -o StrictHostKeyChecking=no root@foo.com -- service stop nginx
      - rsync -v -e ssh root@foo.com:~/copy/file/from send/files/to
      - ssh-o StrictHostKeyChecking=no  root@foo.com -- service start nginx
```

If these examples aren't quite what you are looking for you can always create your own custom plugin. The official plugins are meant to be simple and forkable, so you can always fork and extend to meet your exact needs.

Hope that helps!
