### ISSUE TITLE
Default example being ignored (drone 0.4)

### ISSUE THREAD

**Issue by dgonzalez** [drone-plugins/drone-ssh#22]
This is my `.drone.yaml` file:

```
build:
  image: node
  commands:
    - npm install --development
    - npm test
deploy:
  ssh:
    host: localhost
    user: ubuntu
    port: 22
    script:
      - echo hello
      - echo world
```

The ssh section never gets executed but not sure exactly why (push to master, no PR and the build finishes with success).
